DELIMITER $$

CREATE PROCEDURE InsertInventory(
    IN p_ProductName VARCHAR(255),
    IN p_Barcode VARCHAR(100),
    IN p_Category VARCHAR(255),
    IN p_Supplier VARCHAR(255),
    IN p_Quantity INT,
    IN p_ExpirationDate DATETIME,
    IN p_InventoryNote VARCHAR(255),
    IN p_ProductNote VARCHAR(255)
)
BEGIN
    DECLARE v_CategoryId BIGINT;
    DECLARE v_SupplierId BIGINT;
    DECLARE v_ProductId BIGINT;

    -- CATEGORY: bestaat deze al?
    SELECT Id INTO v_CategoryId
    FROM Category
    WHERE Name COLLATE utf8mb4_unicode_ci = p_Category COLLATE utf8mb4_unicode_ci
    LIMIT 1;

    -- Zo niet → aanmaken
    IF v_CategoryId IS NULL THEN
        INSERT INTO Category (Name)
        VALUES (p_Category);

        SET v_CategoryId = LAST_INSERT_ID();
    END IF;

    -- SUPPLIER: bestaat deze al?
    SELECT Id INTO v_SupplierId
    FROM Supplier
    WHERE CompanyName COLLATE utf8mb4_unicode_ci = p_Supplier COLLATE utf8mb4_unicode_ci
    LIMIT 1;

    -- Zo niet → aanmaken (ContactId verplicht → dummy contact)
    IF v_SupplierId IS NULL THEN
        INSERT INTO Contact (UserId, FirstName, LastName)
        VALUES (1, p_Supplier, 'AutoGenerated');

        INSERT INTO Supplier (CompanyName, ContactId)
        VALUES (p_Supplier, LAST_INSERT_ID());

        SET v_SupplierId = LAST_INSERT_ID();
    END IF;

    -- PRODUCT aanmaken
    INSERT INTO Product (Barcode, ProductName, CategoryId, SupplierId, note)
    VALUES (p_Barcode, p_ProductName, v_CategoryId, v_SupplierId, p_ProductNote);

    SET v_ProductId = LAST_INSERT_ID();

    -- INVENTORY aanmaken
    INSERT INTO Inventory (ProductId, SupplierId, Quantity, ExpirationDate, note)
    VALUES (v_ProductId, v_SupplierId, p_Quantity, p_ExpirationDate, p_InventoryNote);

END $$

DELIMITER ;
